logging:
    file.name: logs/Logs.log
    pattern:
        console: "%d %-5level %logger : %msg%n"
        file: "%d %-5level [%thread] %logger : %msg%n"
    level:
        org.springframework.web: ERROR
        org.hibernate: ERROR
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/IssueTracker
        username: postgres
        password: DudsTheKid3756$

    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

duds_the_kid_3756:
    app:
        jwtSecret: dudsTheKidSecretKey
        jwtExpirationMs: 86400000
